server:
  address: localhost
  port: 8080

spring:
  profiles:
    active: [search]

logging:
  level:
    org:
      springframework:
        session: ERROR
        boot: INFO
        web: INFO
      apache: ERROR
    com:
      sondahum:
        mamas: DEBUG

