server:
  port: 8080
  servlet:
    context-path: /mamas

spring:
  profiles:
    active: [test]

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true

  http:
    encoding:
      charset: euc-kr
      enabled: true
      force: true

#logging:
#  level:
#    org:
#      springframework:
#        session: ERROR
#        boot: ERROR
#        web: ERROR
#      apache: ERROR
#
#
#    com:
#      sondahum:
#        mamas: DEBUG
#
