server:
  port: 8080
  servlet:
    context-path: /mamas

spring:
  profiles:
    active: [test]

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

  http:
    encoding:
      charset: euc-kr
      enabled: true
      force: true

#logging:
#  level:
#    org:
#      springframework:
#        session: ERROR
#        boot: ERROR
#        web: ERROR
#      apache: ERROR
#
#
#    com:
#      sondahum:
#        mamas: DEBUG
#
