spring:
  profiles:
    active: [
      search,
      dev
    ]

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://127.0.0.1:3306/mamas
    username: sondahum
    password: sondahum
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create